import { expect, test } from "@playwright/test";

test("Sasku scoring reference follows named, special and pass-round rules without opening a game", async ({ page }, testInfo) => {
  const externalSockets: string[] = [];
  page.on("websocket", (socket) => { if (!socket.url().includes(":4317")) { externalSockets.push(socket.url()); } });
  await page.setViewportSize({ width: 1440, height: 1100 });
  await page.goto("/");
  await expect(page.getByRole("heading", { name: "Sasku" })).toBeVisible();
  await expect(page.getByRole("button", { name: "Start a game" })).toBeEnabled();
  await expect(page.getByLabel("Invitation link", { exact: true })).toBeVisible();
  await expect(page.locator(".scoring-reference, .hand-practice, .trick-reference, main > header, main > footer")).toHaveCount(0);
  await page.getByRole("link", { name: "Scoring reference" }).click();
  await expect(page).toHaveURL(/\/scoring\.html$/);
  await expect(page.getByRole("heading", { name: "Scoring reference" })).toBeVisible();
  const result = page.getByRole("region", { name: "Example hand score" });
  await expect(result.getByRole("heading", { name: "Seaj\u00e4nn" })).toBeVisible();
  await expect(page.getByLabel("Partnership A game points", { exact: true })).toHaveText("3 P");
  await page.getByLabel("Trump suit", { exact: true }).selectOption("diamonds");
  await expect(page.getByLabel("Partnership A game points", { exact: true })).toHaveText("5 P");
  await page.getByLabel("Who named trump?", { exact: true }).selectOption("1");
  await expect(page.getByLabel("Partnership A game points", { exact: true })).toHaveText("7 P");
  await page.getByLabel("Partnership A card points", { exact: true }).fill("91");
  await expect(result.getByRole("heading", { name: "J\u00e4nn", exact: true })).toBeVisible();
  await expect(page.getByLabel("Partnership A game points", { exact: true })).toHaveText("8 P");
  await page.getByLabel("Partnership A card points", { exact: true }).fill("120");
  await page.getByLabel("Partnership A tricks", { exact: true }).fill("9");
  await expect(result.getByRole("heading", { name: "Karvane" })).toBeVisible();
  await expect(page.getByLabel("Partnership A game points", { exact: true })).toHaveText("12 P");
  await page.getByLabel("How was trump chosen?", { exact: true }).selectOption("pass_round");
  await expect(page.getByLabel("Partnership A game points", { exact: true })).toHaveText("2 P");
  await expect(page.getByLabel("Trump suit", { exact: true })).toBeDisabled();
  await expect(page.getByLabel("Who named trump?", { exact: true })).toBeDisabled();
  await page.getByLabel("Partnership A card points", { exact: true }).fill("60");
  await page.getByLabel("Partnership A tricks", { exact: true }).fill("4");
  await expect(result.getByRole("heading", { name: "Pass-round tie" })).toBeVisible();
  await expect(page.getByLabel("Partnership A game points", { exact: true })).toHaveText("0 P");
  await expect(page.getByLabel("Partnership B game points", { exact: true })).toHaveText("0 P");
  await page.getByLabel("How was trump chosen?", { exact: true }).selectOption("named");
  await expect(result.getByRole("heading", { name: "Pokk" })).toBeVisible();
  await expect(page.getByLabel("Partnership A game points", { exact: true })).toHaveText("2 P");
  await page.locator(".scoring-reference").screenshot({ path: testInfo.outputPath("scoring-desktop.png") });
  await page.setViewportSize({ width: 320, height: 800 });
  await expect.poll(() => page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await expect(page.locator(".court-order li")).toHaveText(["J♦", "J♥", "J♠", "J♣", "Q♦", "Q♥", "Q♠", "Q♣", "K♦", "K♥", "K♠", "K♣"]);
  const heading = page.getByRole("heading", { name: "Scoring reference" });
  expect(await heading.evaluate(element => {
    const range = document.createRange(); range.selectNodeContents(element);
    return range.getClientRects().length;
  })).toBe(1);
  await page.locator(".scoring-reference").screenshot({ path: testInfo.outputPath("scoring-mobile.png") });
  await page.getByLabel("Partnership A card points", { exact: true }).fill("119");
  await expect(result.getByRole("alert")).toContainText("not possible");
  await expect(page.getByLabel("Partnership A game points", { exact: true })).toHaveCount(0);
  expect(externalSockets).toEqual([]);
  await page.getByRole("link", { name: "Back to game" }).click();
  await expect(page.getByRole("button", { name: "Start a game" })).toBeEnabled();
});
